[package]
name = "oracle"
version = "0.1.0"
authors = ["Nina Nikolova <n.nikolova@nolus.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["cosmwasm-bindings"]
cosmwasm-bindings = ["cosmwasm"]
cosmwasm = []
testing = []

[dependencies]
timealarms = { path = "../timealarms", version = "0.1.0", default-features = false }
marketprice = { path = "../../packages/marketprice", version = "0.1.0"}
time-oracle = { path = "../../packages/time-oracle", version = "0.1.0"}
finance = { path = "../../packages/finance", version = "0.1.0", default-features = false }
platform = { path = "../../packages/platform", version = "0.1.0", default-features = false }


cosmwasm-std = "1.0.0"
cosmwasm-storage = "1.0.0"
cw-storage-plus = "0.13.2"
cw2 = "0.13.2"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }


[dev-dependencies]
cosmwasm-schema = "1.0.0"
cw-multi-test = "0.13.0"
timealarms = { path = "../timealarms", version = "0.1.0", default-features = false, features = ["cosmwasm"]}
