[package]
name = "swap"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true
license.workspace = true

resolver = "2"

[features]
trx = ["dep:sdk", "dep:osmosis-std"]

[dependencies]
finance = { path = "../finance", default-features = false }
currency = { path = "../currency", default-features = false }
platform = { path = "../platform", default-features = false }
sdk = { path = "../../packages/sdk", features = ["cosmos"], optional = true }

osmosis-std = { version = "0.12", default-features = false, optional = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
