[package]
name = "swap"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true
license.workspace = true

[dependencies]
finance = { path = "../finance", default-features = false }
currency = { path = "../currency", default-features = false }
# TODO move swap related types to this crate and consume them from the oracle
oracle = { path = "../../contracts/oracle", default-features = false }
platform = { path = "../platform", default-features = false }
sdk = { path = "../../packages/sdk", features = ["cosmos"] }

osmosis-std = { version = "0.12", default-features = false }
thiserror = { workspace = true }

