image: "rust:latest"

stages:
  - test
  - build
  - optimization
  - deploy

.caching_rust: &caching_rust
    cache:
      paths:
        - /usr/local/cargo/
        - target/

.default_rules:
  rules:
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_REF_PROTECTED == "true"

schema:cargo:
  <<: *caching_rust
  stage: test
  variables:
    SCHEMA_DIR: "contracts-schemas"
    SCHEMA_DIR_RESULT: "schemas.tar.gz"
  before_script:
    - apt update && apt install bash
    - apt install curl
    - echo 'y' | apt install jq
  script:
    - cargo install cargo-workspaces
    - cargo workspaces exec --no-bail cargo run --example schema
    - /bin/bash ./scripts/collect-contracts-schemas.sh $SCHEMA_DIR
    - tar -czvf $SCHEMA_DIR_RESULT $SCHEMA_DIR
  artifacts:
    name: "schemas-$CI_COMMIT_REF_SLUG"
    paths:
      - $SCHEMA_DIR_RESULT

test:cargo:
  <<: *caching_rust
  stage: test
  coverage: '/^\d+.\d+% coverage/'
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --out Xml
  artifacts:
    reports:
      cobertura:
        - cobertura.xml

lint:cargo:
  <<: *caching_rust
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --workspace --verbose --all-targets -- -D warnings

build:cargo:
  <<: *caching_rust
  stage: build
  rules:
    - !reference [.default_rules, rules]
  script:
    - rustup target add wasm32-unknown-unknown
    - cargo wasm --target-dir ./target --features cosmwasm
  artifacts:
    paths:
    - target/
    expire_in: 1 hour

optimization:
  stage: optimization
  tags:
    - shell
  rules:
    - !reference [.default_rules, rules]
  script:
    - sudo docker run --rm -v "$(pwd)":/code --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry cosmwasm/workspace-optimizer:0.12.5
  artifacts:
    paths:
    - artifacts/
    expire_in: 1 hour


deploy:cargo:
  <<: *caching_rust
  stage: deploy
  rules:
    - !reference [.default_rules, rules]
  variables:
    CONTRACTS_INFO_FILE: "contracts-info.json"
    CONTRACTS_INFO_DIR: "contracts.tar.gz"
  before_script:
    - apt update && apt install bash
    - apt install curl
    - echo 'y' | apt install jq
  script:
    - /bin/bash ./scripts/deploy-contracts-dev-net.sh $CONTRACTS_INFO_FILE
    - tar -czvf $CONTRACTS_INFO_DIR $CONTRACTS_INFO_FILE
  artifacts:
    name: "contracts-$CI_COMMIT_REF_SLUG"
    paths:
      - $CONTRACTS_INFO_DIR
