stages:
  - prepare
  - check
  - test
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo_home

default:
  # use specific tag here in order to
  # 1) be able to control the build, and
  # 2) update to a newer version. With "latest" and the default '-if-not-present' Docker executor policy that is not possible.
  image: "rust:1.64"

.version_build:
  rules:
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_REF_PROTECTED == "true"

cache:
  paths:
    - cargo_home/

prepare_node:
  stage: prepare
  script:
    - apt update && apt install bash
    - echo 'y' | apt install curl
    - echo 'y' | apt install jq
    - mkdir -p $CARGO_HOME
    - rustc --version && cargo --version
    - cargo install cargo-workspaces

lint:cargo:
  stage: check
  script:
    - ./lint.sh

check_wasm:cargo:
  stage: check
  script:
    - cargo install cosmwasm-check
    - cargo workspaces exec cargo build --target wasm32-unknown-unknown
    - $CARGO_HOME/bin/cosmwasm-check --available-capabilities "staking,stargate,cosmwasm_1_1,iterator,neutron" ./target/wasm32-unknown-unknown/debug/*.wasm

test:cargo:
  stage: test
  coverage: '/^\d+.\d+% coverage/'
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --out Xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

build-and-optimization:cargo:
  stage: build
  tags:
    - shell
  rules:
    - !reference [ .version_build, rules ]
  script:
    - sudo docker run --rm -v "$(pwd)":/code --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target
      --mount type=volume,source=rustup_dir_cache,target=/usr/local/rustup
      --mount type=volume,source=cargo_dir_cache,target=/usr/local/cargo
      --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry
      cosmwasm/workspace-optimizer:0.12.9
    - du -BK artifacts/*.wasm | sed -r 's/K\s+\S+$//' | grep -E '[89][[:digit:]]{2}|[[:digit:]]{4,}' | wc -l | sh -c 'read input; if test "$input" = "0"; then exit 0; else exit 1; fi;'
    - sudo cp scripts/deploy-contracts-genesis.sh artifacts/
  artifacts:
    paths:
      - artifacts/

schema:cargo:
  stage: build
  rules:
    - !reference [ .version_build, rules ]
  variables:
    SCHEMA_DIR: "contracts-schemas"
    SCHEMA_DIR_RESULT: "schemas.tar.gz"
  script:
    - gen_schema() {
        local -r contract="$1" ;
        mkdir "$SCHEMA_DIR/$contract" && cargo run -p "$contract" --example schema -- "$SCHEMA_DIR/$contract" ;
      }
    - rm -fr "$SCHEMA_DIR" && mkdir "$SCHEMA_DIR"
    - gen_schema "lease" && gen_schema "leaser" && gen_schema "lpp" && gen_schema "oracle" && gen_schema "profit" && 
        gen_schema "rewards_dispatcher" && gen_schema "timealarms" && gen_schema "treasury"
    - tar -czvf $SCHEMA_DIR_RESULT $SCHEMA_DIR
  artifacts:
    name: "schemas-$CI_COMMIT_REF_SLUG"
    paths:
      - $SCHEMA_DIR_RESULT
