image: "rust:latest"

.caching_rust: &caching_rust
    cache:
      paths:
        - /usr/local/cargo/
        - target/


schema:cargo:
  <<: *caching_rust
  script:
    - cargo install cargo-workspaces
    - cargo workspaces exec --no-bail cargo run --example schema

# Use cargo to test the project
test:cargo:
  <<: *caching_rust
  coverage: '/^\d+.\d+% coverage/'
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --out Xml
  artifacts:
    reports:
      cobertura:
        - cobertura.xml

lint:cargo:
  <<: *caching_rust
  script:
    - rustup component add clippy
    - cargo clippy --workspace --verbose --all-targets -- -D warnings

deploy:
  image: node:16.14.2-alpine
  variables:
    CONTRACTS_INFO_DIR: "contracts.tar.gz"
  before_script:
    - apk update && apk add bash
    - apk --no-cache add curl
    - apk --no-cache add jq
    - apk add build-essential
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - rustup target add wasm32-unknown-unknown
  script:
    - /bin/bash ./scripts/deploy-contracts-dev-net.sh
    - tar -C contracts-addresses/ -czvf $CONTRACTS_INFO_DIR .
  artifacts:
    name: "contracts-$CI_COMMIT_REF_SLUG"
    paths:
      - $CONTRACTS_INFO_DIR


