image: "rust:latest"

stages:
  - test
  - build
  - deploy

.caching_rust: &caching_rust
    cache:
      paths:
        - /usr/local/cargo/
        - target/

schema:cargo:
  <<: *caching_rust
  stage: test
  script:
    - cargo install cargo-workspaces
    - cargo workspaces exec --no-bail cargo run --example schema

# Use cargo to test the project
test:cargo:
  <<: *caching_rust
  stage: test
  coverage: '/^\d+.\d+% coverage/'
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --out Xml
  artifacts:
    reports:
      cobertura:
        - cobertura.xml

lint:cargo:
  <<: *caching_rust
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --workspace --verbose --all-targets -- -D warnings


optimization:cargo:
  <<: *caching_rust
  stage: build
  tags:
    - shell
  script:
    - rustup target add wasm32-unknown-unknown
    - RUSTFLAGS='-C link-arg=-s' cargo wasm --target-dir ./target
    - sudo docker run --rm -v "$(pwd)":/code --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry cosmwasm/workspace-optimizer:0.12.5


deploy:cargo:
  <<: *caching_rust
  stage: deploy
  variables:
    CONTRACTS_INFO_DIR: "contracts.tar.gz"
  before_script:
    - apt update && apt install bash
    - apt install curl
    - echo 'y' | apt install jq
  script:
    - /bin/bash ./scripts/deploy-contracts-dev-net.sh
    - tar -C contracts-addresses/ $CONTRACTS_INFO_DIR
  artifacts:
    name: "contracts-$CI_COMMIT_REF_SLUG"
    paths:
      - $CONTRACTS_INFO_DIR
