[workspace]
members = ["packages/*", "contracts/*", "tests"]

# TODO use workspace inheritance to manage versions instead of versioning `sdk` package
[workspace.dependencies]
cosmwasm-std = "1.1.4"
cosmwasm-storage = "1.1.4"
cosmwasm-schema = "1.1.4"
cw-storage-plus = "0.15.1"
cw-multi-test = "0.15.1"
# Pinned down to match version of Neutron SDK's Protobuf generated sources
protobuf = "=3.1"

[workspace.dependencies.neutron-sdk]
git = "https://github.com/neutron-org/neutron-contracts"
rev = "e9b2a9d9179d3c136ba024870e762bcb046b0f8c"

[profile.release.package.treasury]
codegen-units = 1
incremental = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
overflow-checks = true
