[workspace]
members = ["packages/*", "contracts/*", "integration_tests"]

[profile.release.package.treasury]
codegen-units = 1
incremental = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
overflow-checks = true
