[package]
name = "schema"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true
license.workspace = true

resolver = "2"

[dependencies]
thiserror = { workspace = true }