[package]
name = "lpp"
version = "0.1.0"
authors = ["v.kolesnikov <v.kolesnikov@nolus.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[example]]
name = "schema"

[features]
default = ["cosmwasm-bindings"]
cosmwasm-bindings = ["cosmwasm"]
cosmwasm = []
testing = []

[dependencies]
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.13.2"
cw2 = "0.13.2"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cosmwasm_protobuf = { path = "../../packages/cosmwasm_protobuf", version = "0.1.0", default-features = false }
finance = { path = "../../packages/finance", version = "0.1.0", default-features = false }
platform = { path = "../../packages/platform", version = "0.1.0", default-features = false }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
