[package]
name = "finance"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition = "2021"

[features]
testing = []

[dependencies]
sdk = { path = "../../packages/sdk", features = ["cosmos", "schema"] }

gcd = "2.1.0"
thiserror = "1.0.37"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
