[package]
name = "finance"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
testing = []

[dependencies]
sdk = { workspace = true, features = ["cosmos", "schema"] }

gcd = "2.1"
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
