[package]
name = "finance"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true

[features]
testing = []

[dependencies]
sdk = { path = "../../packages/sdk", features = ["cosmos", "schema"] }

gcd = "2.1"
thiserror = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
