[package]
name = "leaser"
version = "0.1.0"
authors = ["Nikola Terziev <n.terziev@nolus.io>", "Gancho Manev <g.manev@nolus.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["cosmwasm-bindings"]
cosmwasm-bindings = ["cosmwasm"]
cosmwasm = []


[dependencies]
lease = { path = "../lease", version = "0.1.0", default-features = false }
finance = { path = "../../packages/finance", version = "0.1.0", default-features = false }

cosmwasm-std = { version = "1.0.0-beta6" }
cosmwasm-storage = { version = "1.0.0-beta6" }
cw-storage-plus = "0.13"
cw2 = "0.13"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw-utils = { version = "0.13.1" }


[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta6" }
cw-multi-test = "0.13"
lpp = { path = "../lpp", version = "0.1.0", default-features = false, features = ["cosmwasm"]}
lease = { path = "../lease", version = "0.1.0", default-features = false, features = ["cosmwasm"]}
