[package]
name = "time-oracle"
version = "0.1.0"
authors = ["Vladimir Kolesnikov <v.kolesnikov@nolus.io>"]
edition.workspace = true
license.workspace = true

resolver = "2"

[dependencies]
platform = { path = "../../packages/platform" }
sdk = { path = "../../packages/sdk", features = ["storage"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
