[package]
name = "time-oracle"
version = "0.1.0"
authors = ["Vladimir Kolesnikov <v.kolesnikov@nolus.io>"]
edition.workspace = true

[dependencies]
platform = { path = "../../packages/platform" }
sdk = { path = "../../packages/sdk", features = ["storage"] }

serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = "1"
