[package]
name = "time-oracle"
version = "0.1.0"
authors = ["Vladimir Kolesnikov <v.kolesnikov@nolus.io>"]
edition.workspace = true
license.workspace = true

[dependencies]
platform = { workspace = true }
sdk = { workspace = true, features = ["storage"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
