[package]
name = "time-oracle"
version = "0.1.0"
authors = ["Vladimir Kolesnikov <v.kolesnikov@nolus.io>"]
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.0.0-beta5" }
cw-storage-plus = "0.12"

