[package]
name = "platform"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true

[features]
testing = []

[dependencies]
finance = { path = "../../packages/finance" }
sdk = { path = "../../packages/sdk", features = ["cosmos"] }

prost = "0.11.0"
serde = { version = "1.0.145", default-features = false }
thiserror = "1.0.37"

[dev-dependencies]
finance = { path = "../../packages/finance", features = ["testing"] }
