[package]
name = "platform"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
testing = []

[dependencies]
finance = { path = "../../packages/finance" }
sdk = { path = "../../packages/sdk", features = ["cosmos"] }

prost = "0.11.0"
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
finance = { path = "../../packages/finance", features = ["testing"] }
