[package]
name = "platform"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition = "2021"

[dependencies]
cosmwasm-std = "1.0.0"
serde = { version = "1.0", default-features = false }
thiserror = { version = "1.0" }

finance = { path = "../../packages/finance", version = "0.1.0", default-features = false }
prost = "0.11.0"
