name: 'Check codebase'
description: "Action for checking codebase"
author: "Kiril Mihaylov <k.mihaylov@nolus.io>"

runs:
  using: composite
  steps:
    - name: "Check codebase"
      shell: "sh"
      run: "cargo check"
