[package]
name = "marketprice"
version = "0.1.0"
authors = ["Nina Nikolova <n.nikolova@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
testing = []

[dependencies]
currency = { path = "../../packages/currency" }
finance = { path = "../../packages/finance" }
platform = { path = "../../packages/platform" }
sdk = { path = "../../packages/sdk", features = ["storage", "schema"] }
swap = { path = "../../packages/swap" }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
postcard = { workspace = true, features = ["alloc"] }

[dev-dependencies]
currency = { path = "../../packages/currency", features = ["testing"] }
finance = { path = "../../packages/finance", features = ["testing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { path = "../../packages/sdk", features = ["testing"] }
