[package]
name = "marketprice"
version = "0.1.0"
authors = ["Nina Nikolova <n.nikolova@nolus.io>"]
edition.workspace = true
license.workspace = true

[dependencies]
currency = { path = "../../packages/currency" }
finance = { path = "../../packages/finance" }
platform = { path = "../../packages/platform" }
sdk = { path = "../../packages/sdk", features = ["storage", "schema"] }

thiserror = "1"
serde = { version = "1", default-features = false, features = ["derive"] }

[dev-dependencies]
currency = { path = "../../packages/currency", features = ["testing"] }
finance = { path = "../../packages/finance", features = ["testing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
sdk = { path = "../../packages/sdk", features = ["testing"] }
