[package]
name = "currency"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition.workspace = true
license.workspace = true

resolver = "2"

[features]
testing = []

[dependencies]
finance = { path = "../../packages/finance" }
sdk = { path = "../../packages/sdk", features = ["schema"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
finance = { path = "../../packages/finance", features = ["testing"] }
