[package]
name = "currency"
version = "0.1.0"
authors = ["Gancho Manev <g.manev@nolus.io>"]
edition = "2021"

[features]
testing = []

[dependencies]
finance = { path = "../../packages/finance" }
sdk = { path = "../../packages/sdk", features = ["schema"] }

thiserror = "1.0"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
