name: General Rust Workflow
run-name: "Building Rust by ${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"

env:
  CARGO_TERM_COLOR: "always"

jobs:
  check-lock-file:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Check Formatting"
        run: "cargo check -p sdk --locked"
  check-formatting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Check Formatting"
        run: "cargo fmt --check"
  check-dependencies:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install cargo-audit"
        run: "cargo install cargo-audit"
      - name: "Audit dependencies"
        run: "cargo audit"
  linting:
    runs-on: "ubuntu-latest"
    needs:
      - "check-formatting"
      - "check-dependencies"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Installing linter"
        run: "rustup component add clippy"
      - name: "Running linter"
        run: "cargo clippy --all-targets"
  test:
    runs-on: "ubuntu-latest"
    needs:
      - "linting"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Running tests"
        run: "cargo test"
