name: Rust
run-name: "${{ github.actor }} is "

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: "always"

jobs:
  check-formatting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Check Formatting"
        run: "cargo fmt --check"
  check-dependencies:
    runs-on: "ubuntu-latest"
    needs:
      - "check-formatting"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install cargo-audit"
        run: "cargo install cargo-audit"
      - name: "Audit dependencies"
        run: "cargo audit"
